"""add missing fields to drive_round, eligibility, workflow

Revision ID: 7b0778dd1f37
Revises: f6c59defc559
Create Date: 2026-03-28 16:44:28.439583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0778dd1f37'
down_revision: Union[str, Sequence[str], None] = 'f6c59defc559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_rounds', sa.Column('round_date', sa.Date(), nullable=True))
    op.add_column('drive_rounds', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('eligibility_rules', sa.Column('min_batch', sa.Integer(), nullable=True))
    op.add_column('eligibility_rules', sa.Column('max_batch', sa.Integer(), nullable=True))
    op.add_column('eligibility_rules', sa.Column('other_criteria', sa.String(), nullable=True))
    op.add_column('eligibility_rules', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflows', sa.Column('total_rounds', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'updated_at')
    op.drop_column('workflows', 'total_rounds')
    op.drop_column('eligibility_rules', 'updated_at')
    op.drop_column('eligibility_rules', 'other_criteria')
    op.drop_column('eligibility_rules', 'max_batch')
    op.drop_column('eligibility_rules', 'min_batch')
    op.drop_column('drive_rounds', 'updated_at')
    op.drop_column('drive_rounds', 'round_date')
    # ### end Alembic commands ###
