"""add eligibility

Revision ID: f6c59defc559
Revises: 7d3ee95288db
Create Date: 2026-03-28 16:07:56.683591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c59defc559'
down_revision: Union[str, Sequence[str], None] = '7d3ee95288db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('max_backlogs', sa.Integer(), nullable=True),
    sa.Column('min_backlogs', sa.Integer(), nullable=True),
    sa.Column('allowed_branches', sa.String(), nullable=True),
    sa.Column('gender_restriction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rules_id'), 'eligibility_rules', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('drive_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_rounds_id'), 'drive_rounds', ['id'], unique=False)
    op.drop_index(op.f('ix_student_application_id'), table_name='student_application')
    op.drop_table('student_application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drive_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], name=op.f('student_application_drive_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_application_pkey'))
    )
    op.create_index(op.f('ix_student_application_id'), 'student_application', ['id'], unique=False)
    op.drop_index(op.f('ix_drive_rounds_id'), table_name='drive_rounds')
    op.drop_table('drive_rounds')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_eligibility_rules_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    # ### end Alembic commands ###
