from pydantic import BaseModel, EmailStr
from typing import Optional


# 📥 Request Schema
class CompanyCreate(BaseModel):
    name: str 
    industry: str
    website: str
    address: str
    hr_contact_name: Optional[str] = None
    hr_contact_email: Optional[EmailStr] = None
    hr_contact_phone: Optional[str] = None
    is_approved: Optional[bool] = False


# 📤 Response Schema
class CompanyResponse(BaseModel):
    id: int
    name: str
    industry: str
    website: str
    address: str
    hr_contact_name: Optional[str]
    hr_contact_email: Optional[EmailStr]
    hr_contact_phone: Optional[str]
    is_approved: bool




class CompanyUpdate(BaseModel):
    name: Optional[str] = None
    industry: Optional[str] = None
    website: Optional[str] = None
    address: Optional[str] = None
    hr_contact_name: Optional[str] = None
    hr_contact_email: Optional[EmailStr] = None
    hr_contact_phone: Optional[str] = None
    is_approved: Optional[bool] = None

    class Config:
        from_attributes = True


# from pydantic import BaseModel, EmailStr
# from typing import Optional

# #schemas are used to define the structure of the data which will be used in the request body and response body, we are using Pydantic to define the schemas, Pydantic provides validation and serialization of the data, we are defining the fields which are required to create a company and to return the company details in the response when we create a company, these fields will be used in the request body when creating a company and in the response body when returning the company details after creating a company

# class CompanyCreate(BaseModel): #this class is used to define the schema for creating a company, it inherits from BaseModel which is provided by Pydantic, BaseModel provides validation and serialization of the data, we are defining the fields which are required to create a company, these fields will be used in the request body when creating a company
#     name: str
#     industry: str
#     website: str
#     address : str
#     hr_contact_name: Optional[str]= None
#     hr_contact_email: Optional[str]= None
#     hr_contact_phone: Optional[str]= None
#     is_approved: Optional[bool] = False
    

# class CompanyResponse(CompanyCreate): #if we dont write this class then we will not be able to return the company details in the response when we create a company, because the CompanyCreate class does not have the id field which is generated by the database, so we need to create a new class which inherits from CompanyCreate and adds the id field to it, this way we can return the company details in the response when we create a company
#     id: int

# class Config: #this is used to configure the Pydantic model, we are setting orm_mode to True which allows us to return the company details in the response when we create a company, because the Company model which we have created in models.py is an ORM model and it does not have the same fields as the CompanyCreate class, so we need to set orm_mode to True to allow Pydantic to convert the ORM model to the Pydantic model when we return the company details in the response
#         orm_mode = True